const canvas=document.querySelector('#editorCanvas'), ctx=canvas.getContext('2d'), empty=document.querySelector('#emptyState');
const wrap=document.querySelector('#canvasWrap'), toast=document.querySelector('#toast'), props=document.querySelector('#properties'), none=document.querySelector('#noSelection');
let image=null, annotations=[], tool='select', color='#D7FF4A', opacity=.45, weight=6, drawing=null, zoom=1, history=[];
function save(){history.push(JSON.stringify({annotations, image:image?.src, w:canvas.width,h:canvas.height})); if(history.length>30)history.shift()}
function restore(){if(history.length<2)return show('Nothing more to undo');history.pop();const state=JSON.parse(history.at(-1));canvas.width=state.w;canvas.height=state.h;wrap.style.width=canvas.width+'px';annotations=state.annotations||[];if(state.image){image=new Image();image.onload=render;image.src=state.image}else{image=null;render()}}
function setCanvas(img){image=img; const maxW=1280,maxH=800,r=Math.min(maxW/img.width,maxH/img.height,1);canvas.width=Math.round(img.width*r);canvas.height=Math.round(img.height*r);annotations=[];empty.style.display='none';wrap.style.width=canvas.width+'px';save();render();show('Capture added to canvas')}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);if(image)ctx.drawImage(image,0,0,canvas.width,canvas.height);annotations.forEach(drawAnnotation);if(drawing)drawAnnotation(drawing)}
function drawAnnotation(a){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=a.color;ctx.fillStyle=a.color;ctx.lineWidth=a.weight||6;ctx.globalAlpha=a.opacity??1;
 if(a.type==='highlight'){ctx.globalAlpha=a.opacity;ctx.fillRect(a.x,a.y,a.w,a.h)}
 if(a.type==='draw'){ctx.globalAlpha=1;ctx.beginPath();a.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}
 if(a.type==='arrow'){ctx.globalAlpha=1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+a.w,a.y+a.h);ctx.stroke();const angle=Math.atan2(a.h,a.w),s=13+a.weight;ctx.beginPath();ctx.moveTo(a.x+a.w,a.y+a.h);ctx.lineTo(a.x+a.w-s*Math.cos(angle-.45),a.y+a.h-s*Math.sin(angle-.45));ctx.moveTo(a.x+a.w,a.y+a.h);ctx.lineTo(a.x+a.w-s*Math.cos(angle+.45),a.y+a.h-s*Math.sin(angle+.45));ctx.stroke()}
 if(a.type==='text'){ctx.globalAlpha=1;ctx.font=`${Math.max(16,a.weight*4)}px Manrope`;ctx.fillText(a.text,a.x,a.y)}
 if(a.type==='crop'){ctx.globalAlpha=.72;ctx.fillStyle='#172013';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.clearRect(a.x,a.y,a.w,a.h);ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.setLineDash([7,5]);ctx.strokeRect(a.x,a.y,a.w,a.h)}ctx.restore()}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.addEventListener('pointerdown',e=>{if(!image)return;const p=point(e);if(tool==='select')return;if(tool==='text'){const text=prompt('Add a note');if(text){annotations.push({type:'text',x:p.x,y:p.y,text,color,weight});save();render()}return}drawing={type:tool,x:p.x,y:p.y,w:0,h:0,color,opacity,weight,points:tool==='draw'?[p]:undefined};canvas.setPointerCapture(e.pointerId);render()});
canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);if(drawing.type==='draw')drawing.points.push(p);else{drawing.w=p.x-drawing.x;drawing.h=p.y-drawing.y}render()});
canvas.addEventListener('pointerup',e=>{if(!drawing)return;if(Math.abs(drawing.w||0)>3||(drawing.type==='arrow'&&Math.abs(drawing.h||0)>3)||drawing.type==='draw'){annotations.push(drawing);save()}drawing=null;render()});
function selectTool(next){tool=next;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===next));canvas.style.cursor=next==='select'?'default':'crosshair';const active=next!=='select';props.hidden=!active;none.hidden=active;document.querySelector('#cropActions').hidden=next!=='crop'}
document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));
document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{color=b.dataset.color;document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
document.querySelector('#colorPicker').oninput=e=>{color=e.target.value;document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'))};
document.querySelector('#opacityRange').oninput=e=>{opacity=e.target.value/100;document.querySelector('#opacityOutput').value=e.target.value+'%'};
document.querySelectorAll('[data-weight]').forEach(b=>b.onclick=()=>{weight=+b.dataset.weight;document.querySelectorAll('[data-weight]').forEach(x=>x.classList.toggle('selected',x===b));document.querySelector('#weightOutput').value=weight+' px'});
function show(s){toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function openFile(){document.querySelector('#fileInput').click()} document.querySelector('#uploadBtn').onclick=openFile; document.querySelector('#fileInput').onchange=e=>loadFile(e.target.files[0]);
function loadFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>setCanvas(img);img.src=reader.result};reader.readAsDataURL(file)}
async function capture(){try{const stream=await navigator.mediaDevices.getDisplayMedia({video:{cursor:'always'},audio:false});const video=document.createElement('video');video.srcObject=stream;await video.play();const img=new Image(), tmp=document.createElement('canvas');tmp.width=video.videoWidth;tmp.height=video.videoHeight;tmp.getContext('2d').drawImage(video,0,0);img.onload=()=>setCanvas(img);img.src=tmp.toDataURL('image/png');stream.getTracks().forEach(t=>t.stop())}catch(e){show('Screen capture was cancelled')}}document.querySelector('#screenCapture').onclick=capture;document.querySelector('#emptyCapture').onclick=capture;
document.addEventListener('paste',e=>{const f=[...e.clipboardData.files].find(x=>x.type.startsWith('image/'));if(f)loadFile(f)});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();capture()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){restore()}const map={h:'highlight',d:'draw',a:'arrow',t:'text',c:'crop',v:'select'};if(map[e.key.toLowerCase()]&&!e.metaKey)selectTool(map[e.key.toLowerCase()])});
document.querySelector('#undoBtn').onclick=restore;document.querySelector('#redoBtn').onclick=()=>show('Redo is available after a new edit');document.querySelector('#deleteBtn').onclick=()=>{if(annotations.length){annotations.pop();save();render();show('Last annotation removed')}};
document.querySelector('#applyCrop').onclick=()=>{const c=annotations.filter(a=>a.type==='crop').at(-1);if(!c)return show('Draw a crop area first');const cropAnnotations=annotations.filter(a=>a.type==='crop');annotations=annotations.filter(a=>a.type!=='crop');render();const temp=document.createElement('canvas');temp.width=Math.abs(c.w);temp.height=Math.abs(c.h);temp.getContext('2d').drawImage(canvas,Math.min(c.x,c.x+c.w),Math.min(c.y,c.y+c.h),Math.abs(c.w),Math.abs(c.h),0,0,temp.width,temp.height);annotations=cropAnnotations;render();const img=new Image();img.onload=()=>setCanvas(img);img.src=temp.toDataURL();};document.querySelector('#cancelCrop').onclick=()=>{annotations=annotations.filter(a=>a.type!=='crop');render();selectTool('select')};
document.querySelector('#downloadBtn').onclick=()=>{if(!image)return show('Add a capture before exporting');const a=document.createElement('a');a.download='clario-capture.png';a.href=canvas.toDataURL('image/png');a.click();show('PNG export downloaded')};
document.querySelector('#shareBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);show('Share link copied to clipboard')}catch{show('Your capture is ready to share')}};
document.querySelector('#renameBtn').onclick=()=>{const n=prompt('Name this capture',document.querySelector('#documentName').textContent);if(n)document.querySelector('#documentName').textContent=n};
function setZoom(v){zoom=Math.max(.35,Math.min(1.5,v));wrap.style.transform=`scale(${zoom})`;wrap.style.transformOrigin='center';document.querySelector('#zoomValue').textContent=Math.round(zoom*100)+'%'}document.querySelector('#zoomIn').onclick=()=>setZoom(zoom+.1);document.querySelector('#zoomOut').onclick=()=>setZoom(zoom-.1);document.querySelector('#fitBtn').onclick=()=>setZoom(1);
